---
  - name: verify install java
    command: dpkg -s oracle-java{{ java_version }}-set-default
    register: java_already_install
    ignore_errors: True

  - name: update
    when: java_already_install | failed
    shell: apt-get update -y
    become: yes
    become_method: sudo

  - name: update python
    when: java_already_install | failed
    shell: apt-get install python-software-properties -y
    become: yes
    become_method: sudo

  - name: updating and installing java repo
    when: java_already_install | failed
    shell:
        add-apt-repository ppa:webupd8team/java
    args:
        executable: /bin/bash
    become: yes
    become_method: sudo
    register: repo_add

  - name: apt-get update
    when: java_already_install | failed
    apt:
      update_cache: yes
    become: yes
    become_method: sudo
    register: update_cache

  - name: accept java license
    when: java_already_install | failed
    debconf: name="oracle-java{{ java_version }}-installer" question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
    become: yes
    become_method: sudo
    register: license_accept

  - name: install oracle java
    when: java_already_install | failed
    apt: name={{item}} state=latest
    with_items:
      - "oracle-java{{ java_version }}-installer"
      - ca-certificates
      - "oracle-java{{ java_version }}-set-default"
    become: yes
    become_method: sudo
