---
  - name: nginx start
    service:
      name: nginx
      state: started
    become: yes
    become_method: sudo

  - name: nginx restart
    service:
      name: nginx
      state: restarted
    become: yes
    become_method: sudo

  - name: nginx stop
    service:
      name: nginx
      state: stopped
    become: yes
    become_method: sudo
