---
  - name: tomcat start
    service:
      name: tomcat
      state: started
    become: yes
    become_method: sudo

  - name: tomcat restart
    service:
      name: tomcat
      state: restarted
    become: yes
    become_method: sudo

  - name: tomcat stop
    service:
      name: tomcat
      state: stopped
    become: yes
    become_method: sudo
