---
  - name: tomcat start
    service:
      name: tomcat
      state: started
    sudo: yes

  - name: tomcat restart
    service:
      name: tomcat
      state: restarted
    sudo: yes

  - name: tomcat stop
    service:
      name: tomcat
      state: stopped
    sudo: yes
