---
  - name: verify install nginx
    command: dpkg -s nginx
    register: nginx_already_install
    notify:
      - nginx start
      - nginx restart
    ignore_errors: True

  - name: install nginx
    when: nginx_already_install | failed
    apt:
      name: nginx
      update_cache: yes
    become: yes
    become_method: sudo
    notify:
      - nginx start
    register: nginx_installed


  - name: add nginx config
    when: nginx_installed | success
    template:
      src: /home/kamyshev/ansible-tasks-days/ansible/day-3/roles/nginx/template/tomcat.conf
      dest: /etc/nginx/conf.d/tomcat.conf
    notify:
      - nginx restart
    become: yes
    become_method: sudo
